# Generated by Django 4.1.1 on 2022-10-01 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PregenerateUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('shorten_url_hash', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('INACTIVE', 'inactive'), ('ACTIVE', 'active')], default='inactive', max_length=10)),
            ],
        ),
    ]
