# Generated by Django 4.1.1 on 2022-10-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pregenerate_url', '0002_pregenerateurl_created_at_pregenerateurl_updated_at'),
        ('shorten_url', '0002_shortenurl_created_at_shortenurl_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenurl',
            name='pregenerate_url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pregenerate_url.pregenerateurl'),
            preserve_default=False,
        ),
    ]
